# Generated by Django 4.0 on 2021-12-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_genre_alter_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
