# Generated by Django 4.0 on 2022-01-24 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='origincountry',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='releasedDate',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='writer',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
