# Generated by Django 4.0 on 2022-01-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_movie_slug_alter_movie_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='slug',
        ),
    ]
