# Generated by Django 4.0 on 2022-01-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_remove_movie_certificate_remove_movie_poster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='releasedDate',
            field=models.CharField(max_length=200),
        ),
    ]
